Repository gardener/machine-controller-manager-provider-alicloud, pull requests merged in 2020-12, with the labels that each got.

#1 Support Gardener credentials data keys
  kubernetes/secret.yaml
  pkg/spi/spi.go
Labels: area/open-source, area/usability, kind/enhancement, platform/alicloud, priority/normal, reviewed/lgtm, size/xs

#2 Implement MCM migration method
  go.mod
  go.sum
  pkg/alicloud/apis/alicloud_provider_spec.go
  pkg/alicloud/machine_controller.go
  pkg/alicloud/machine_controller_test.go
  pkg/alicloud/machine_controller_util.go
  pkg/alicloud/migration.go
  pkg/spi/spi_test.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/alicoud_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/aws_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/azure_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/gcp_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machine_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/openstack_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/packet_machineclass_types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/validation/azuremachineclass.go
  vendor/github.com/gardener/machine-controller-manager/pkg/apis/machine/zz_generated.deepcopy.go
  vendor/github.com/gardener/machine-controller-manager/pkg/options/types.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/nodeops/conditions.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/nodeops/taints.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/app/options/options.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/drain/drain.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/controller.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine_safety.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine_util.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machineclass.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/migrate_machineclass.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/secret.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/secret_util.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machineutils/utils.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/strings/string.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/taints/taints.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/time/time.go
  vendor/github.com/jmespath/go-jmespath/.gitignore
  vendor/github.com/jmespath/go-jmespath/api.go
  vendor/modules.txt
Labels: reviewed/lgtm, size/m

#3 implement ci pipeline
  .ci/build
  .ci/check
  .ci/pipeline_definitions
  .ci/setupenv.src
  .ci/test
Labels: needs/review, size/m

#4 grant executing permission of scripts
  .ci/build
  .ci/check
  .ci/pipeline_definitions
  .ci/setupenv.src
  .ci/test
Labels: needs/ok-to-test, needs/review, size/xs

#5 enhance unit test cases
  go.mod
  go.sum
  pkg/alicloud/machine_controller_test.go
  pkg/mock/client.go
  pkg/mock/client/doc.go
  pkg/mock/client/mocks.go
  pkg/mock/spi.go
  pkg/mock/spi/doc.go
  pkg/mock/spi/mocks.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#7 update golang and alpine version
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#8 change equal to consistof for slice
  pkg/alicloud/machine_controller_test.go
  pkg/spi/spi_test.go
Labels: needs/ok-to-test, needs/review, size/s
