Repository gardener/machine-controller-manager-provider-alicloud, pull requests merged in 2022-05, with the labels that each got.

#23 alpine and golang images updated
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#26 Pin github.com/prometheus/client_golang to v1.12.1
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/LICENSE.txt
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/README.md
  vendor/github.com/prometheus/client_golang/prometheus/build_info_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go117.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: kind/regression, reviewed/lgtm, needs/ok-to-test, size/xs

#27 [rel-v0.4] Automated cherry pick of #26: Pin github.com/prometheus/client_golang to v1.12.1
  go.mod
  go.sum
  vendor/github.com/cespare/xxhash/v2/LICENSE.txt
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_other.go
  vendor/github.com/cespare/xxhash/v2/xxhash_safe.go
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/metrics/metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/README.md
  vendor/github.com/prometheus/client_golang/prometheus/build_info_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go117.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: kind/regression, reviewed/ok-to-test, reviewed/do-not-merge, needs/review, size/xs
