Repository gardener/machine-controller-manager-provider-alicloud, pull requests merged in 2023-02, with the labels that each got.

#39 Vendor mcm 0.48.1
  go.mod
  go.sum
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine_bootstrap_token.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/xs

#40 Vendor mcm 0.47.1
  go.mod
  go.sum
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine.go
  vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine_bootstrap_token.go
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#41 Enable auto vendoring of MCM dependency
  .ci/component_descriptor
  .ci/pipeline_definitions
  .ci/set_dependency_version
  MCM_VERSION
Labels: reviewed/lgtm, needs/ok-to-test, size/s
