Repository gardener/machine-controller-manager-provider-alicloud, pull requests merged in 2023-12, with the labels that each got.

#62 Update testmachinery image location
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#63 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  kubernetes/deployment.yaml
Labels: needs/ok-to-test, needs/review, size/s

#64 Enhance IT pipeline
  .ci/pipeline_integration_test
Labels: reviewed/lgtm, needs/ok-to-test, size/m
